version: 2

sources:
  - name: airbnb_raw
    schema: raw
    tables:
       - name: listings
         identifier: raw_listings
       - name: hosts
         identifier: raw_hosts
         freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}
       - name: reviews
         identifier: raw_reviews
         freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}

  - name: airbnb_dev
    schema: dev
    tables:
       - name: fct_reviews
         identifier: fct_reviews